// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fk-module.proto

/*
Package fk_module is a generated protocol buffer package.

It is generated from these files:
	fk-module.proto

It has these top-level messages:
	QueryCapabilities
	QuerySensorCapabilities
	Firmware
	Capabilities
	FirmwareReply
	SensorCapabilities
	BeginTakeReadings
	QueryReadingStatus
	ReadingStatus
	SensorReadings
	SensorReading
	Custom
	Data
	DataStatus
	BeginTransmission
	QueryTransmissionStatus
	TransmissionStatus
	WireMessageQuery
	Error
	WireMessageReply
*/
package fk_module

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryType int32

const (
	QueryType_QUERY_NONE                QueryType = 0
	QueryType_QUERY_CAPABILITIES        QueryType = 1
	QueryType_QUERY_SENSOR_CAPABILITIES QueryType = 2
	QueryType_QUERY_BEGIN_TAKE_READINGS QueryType = 3
	QueryType_QUERY_READING_STATUS      QueryType = 4
	QueryType_QUERY_CUSTOM              QueryType = 5
	QueryType_QUERY_DATA_APPEND         QueryType = 6
	QueryType_QUERY_DATA_CLEAR          QueryType = 7
	QueryType_QUERY_BEGIN_TRANSMISSION  QueryType = 8
	QueryType_QUERY_TRANSMISSION_STATUS QueryType = 9
	QueryType_QUERY_DATA_PREPARE        QueryType = 10
	QueryType_QUERY_DATA_VERIFY         QueryType = 11
	QueryType_QUERY_FIRMWARE            QueryType = 12
)

var QueryType_name = map[int32]string{
	0:  "QUERY_NONE",
	1:  "QUERY_CAPABILITIES",
	2:  "QUERY_SENSOR_CAPABILITIES",
	3:  "QUERY_BEGIN_TAKE_READINGS",
	4:  "QUERY_READING_STATUS",
	5:  "QUERY_CUSTOM",
	6:  "QUERY_DATA_APPEND",
	7:  "QUERY_DATA_CLEAR",
	8:  "QUERY_BEGIN_TRANSMISSION",
	9:  "QUERY_TRANSMISSION_STATUS",
	10: "QUERY_DATA_PREPARE",
	11: "QUERY_DATA_VERIFY",
	12: "QUERY_FIRMWARE",
}
var QueryType_value = map[string]int32{
	"QUERY_NONE":                0,
	"QUERY_CAPABILITIES":        1,
	"QUERY_SENSOR_CAPABILITIES": 2,
	"QUERY_BEGIN_TAKE_READINGS": 3,
	"QUERY_READING_STATUS":      4,
	"QUERY_CUSTOM":              5,
	"QUERY_DATA_APPEND":         6,
	"QUERY_DATA_CLEAR":          7,
	"QUERY_BEGIN_TRANSMISSION":  8,
	"QUERY_TRANSMISSION_STATUS": 9,
	"QUERY_DATA_PREPARE":        10,
	"QUERY_DATA_VERIFY":         11,
	"QUERY_FIRMWARE":            12,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReplyType int32

const (
	ReplyType_REPLY_NONE                ReplyType = 0
	ReplyType_REPLY_RETRY               ReplyType = 1
	ReplyType_REPLY_ERROR               ReplyType = 2
	ReplyType_REPLY_CAPABILITIES        ReplyType = 3
	ReplyType_REPLY_SENSOR_CAPABILITIES ReplyType = 4
	ReplyType_REPLY_READING_STATUS      ReplyType = 5
	ReplyType_REPLY_CUSTOM              ReplyType = 6
	ReplyType_REPLY_DATA                ReplyType = 7
	ReplyType_REPLY_TRANSMISSION_STATUS ReplyType = 8
	ReplyType_REPLY_SUCCESS             ReplyType = 9
	ReplyType_REPLY_BUSY                ReplyType = 10
	ReplyType_REPLY_FIRMWARE            ReplyType = 11
)

var ReplyType_name = map[int32]string{
	0:  "REPLY_NONE",
	1:  "REPLY_RETRY",
	2:  "REPLY_ERROR",
	3:  "REPLY_CAPABILITIES",
	4:  "REPLY_SENSOR_CAPABILITIES",
	5:  "REPLY_READING_STATUS",
	6:  "REPLY_CUSTOM",
	7:  "REPLY_DATA",
	8:  "REPLY_TRANSMISSION_STATUS",
	9:  "REPLY_SUCCESS",
	10: "REPLY_BUSY",
	11: "REPLY_FIRMWARE",
}
var ReplyType_value = map[string]int32{
	"REPLY_NONE":                0,
	"REPLY_RETRY":               1,
	"REPLY_ERROR":               2,
	"REPLY_CAPABILITIES":        3,
	"REPLY_SENSOR_CAPABILITIES": 4,
	"REPLY_READING_STATUS":      5,
	"REPLY_CUSTOM":              6,
	"REPLY_DATA":                7,
	"REPLY_TRANSMISSION_STATUS": 8,
	"REPLY_SUCCESS":             9,
	"REPLY_BUSY":                10,
	"REPLY_FIRMWARE":            11,
}

func (x ReplyType) String() string {
	return proto.EnumName(ReplyType_name, int32(x))
}
func (ReplyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ModuleType int32

const (
	ModuleType_SENSOR         ModuleType = 0
	ModuleType_COMMUNICATIONS ModuleType = 1
)

var ModuleType_name = map[int32]string{
	0: "SENSOR",
	1: "COMMUNICATIONS",
}
var ModuleType_value = map[string]int32{
	"SENSOR":         0,
	"COMMUNICATIONS": 1,
}

func (x ModuleType) String() string {
	return proto.EnumName(ModuleType_name, int32(x))
}
func (ModuleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadingState int32

const (
	ReadingState_IDLE  ReadingState = 0
	ReadingState_BEGIN ReadingState = 1
	ReadingState_BUSY  ReadingState = 2
	ReadingState_DONE  ReadingState = 3
)

var ReadingState_name = map[int32]string{
	0: "IDLE",
	1: "BEGIN",
	2: "BUSY",
	3: "DONE",
}
var ReadingState_value = map[string]int32{
	"IDLE":  0,
	"BEGIN": 1,
	"BUSY":  2,
	"DONE":  3,
}

func (x ReadingState) String() string {
	return proto.EnumName(ReadingState_name, int32(x))
}
func (ReadingState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RequiredUptime int32

const (
	RequiredUptime_ALWAYS        RequiredUptime = 0
	RequiredUptime_READINGS_ONLY RequiredUptime = 1
)

var RequiredUptime_name = map[int32]string{
	0: "ALWAYS",
	1: "READINGS_ONLY",
}
var RequiredUptime_value = map[string]int32{
	"ALWAYS":        0,
	"READINGS_ONLY": 1,
}

func (x RequiredUptime) String() string {
	return proto.EnumName(RequiredUptime_name, int32(x))
}
func (RequiredUptime) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TransmissionState int32

const (
	TransmissionState_TRANSMISSION_IDLE  TransmissionState = 0
	TransmissionState_TRANSMISSION_BEGIN TransmissionState = 1
	TransmissionState_TRANSMISSION_BUSY  TransmissionState = 2
	TransmissionState_TRANSMISSION_DONE  TransmissionState = 3
)

var TransmissionState_name = map[int32]string{
	0: "TRANSMISSION_IDLE",
	1: "TRANSMISSION_BEGIN",
	2: "TRANSMISSION_BUSY",
	3: "TRANSMISSION_DONE",
}
var TransmissionState_value = map[string]int32{
	"TRANSMISSION_IDLE":  0,
	"TRANSMISSION_BEGIN": 1,
	"TRANSMISSION_BUSY":  2,
	"TRANSMISSION_DONE":  3,
}

func (x TransmissionState) String() string {
	return proto.EnumName(TransmissionState_name, int32(x))
}
func (TransmissionState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ErrorType int32

const (
	ErrorType_NONE       ErrorType = 0
	ErrorType_GENERAL    ErrorType = 1
	ErrorType_UNEXPECTED ErrorType = 2
)

var ErrorType_name = map[int32]string{
	0: "NONE",
	1: "GENERAL",
	2: "UNEXPECTED",
}
var ErrorType_value = map[string]int32{
	"NONE":       0,
	"GENERAL":    1,
	"UNEXPECTED": 2,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type QueryCapabilities struct {
	Version    int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	CallerTime uint32 `protobuf:"varint,2,opt,name=callerTime" json:"callerTime,omitempty"`
}

func (m *QueryCapabilities) Reset()                    { *m = QueryCapabilities{} }
func (m *QueryCapabilities) String() string            { return proto.CompactTextString(m) }
func (*QueryCapabilities) ProtoMessage()               {}
func (*QueryCapabilities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryCapabilities) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *QueryCapabilities) GetCallerTime() uint32 {
	if m != nil {
		return m.CallerTime
	}
	return 0
}

type QuerySensorCapabilities struct {
	Sensor int32 `protobuf:"varint,1,opt,name=sensor" json:"sensor,omitempty"`
}

func (m *QuerySensorCapabilities) Reset()                    { *m = QuerySensorCapabilities{} }
func (m *QuerySensorCapabilities) String() string            { return proto.CompactTextString(m) }
func (*QuerySensorCapabilities) ProtoMessage()               {}
func (*QuerySensorCapabilities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QuerySensorCapabilities) GetSensor() int32 {
	if m != nil {
		return m.Sensor
	}
	return 0
}

type Firmware struct {
	Git   string `protobuf:"bytes,1,opt,name=git" json:"git,omitempty"`
	Build string `protobuf:"bytes,2,opt,name=build" json:"build,omitempty"`
	Size  uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Etag  string `protobuf:"bytes,4,opt,name=etag" json:"etag,omitempty"`
	Time  uint32 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *Firmware) Reset()                    { *m = Firmware{} }
func (m *Firmware) String() string            { return proto.CompactTextString(m) }
func (*Firmware) ProtoMessage()               {}
func (*Firmware) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Firmware) GetGit() string {
	if m != nil {
		return m.Git
	}
	return ""
}

func (m *Firmware) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *Firmware) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Firmware) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Firmware) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Capabilities struct {
	Version                 int32          `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Type                    ModuleType     `protobuf:"varint,2,opt,name=type,enum=fk_module.ModuleType" json:"type,omitempty"`
	Name                    string         `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Module                  string         `protobuf:"bytes,7,opt,name=module" json:"module,omitempty"`
	NumberOfSensors         int32          `protobuf:"varint,4,opt,name=numberOfSensors" json:"numberOfSensors,omitempty"`
	Firmware                *Firmware      `protobuf:"bytes,5,opt,name=firmware" json:"firmware,omitempty"`
	MinimumNumberOfReadings int32          `protobuf:"varint,6,opt,name=minimumNumberOfReadings" json:"minimumNumberOfReadings,omitempty"`
	Compiled                uint32         `protobuf:"varint,8,opt,name=compiled" json:"compiled,omitempty"`
	RequiredUptime          RequiredUptime `protobuf:"varint,9,opt,name=requiredUptime,enum=fk_module.RequiredUptime" json:"requiredUptime,omitempty"`
}

func (m *Capabilities) Reset()                    { *m = Capabilities{} }
func (m *Capabilities) String() string            { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()               {}
func (*Capabilities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Capabilities) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Capabilities) GetType() ModuleType {
	if m != nil {
		return m.Type
	}
	return ModuleType_SENSOR
}

func (m *Capabilities) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Capabilities) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Capabilities) GetNumberOfSensors() int32 {
	if m != nil {
		return m.NumberOfSensors
	}
	return 0
}

func (m *Capabilities) GetFirmware() *Firmware {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func (m *Capabilities) GetMinimumNumberOfReadings() int32 {
	if m != nil {
		return m.MinimumNumberOfReadings
	}
	return 0
}

func (m *Capabilities) GetCompiled() uint32 {
	if m != nil {
		return m.Compiled
	}
	return 0
}

func (m *Capabilities) GetRequiredUptime() RequiredUptime {
	if m != nil {
		return m.RequiredUptime
	}
	return RequiredUptime_ALWAYS
}

type FirmwareReply struct {
	Good    *Firmware `protobuf:"bytes,1,opt,name=good" json:"good,omitempty"`
	Pending *Firmware `protobuf:"bytes,2,opt,name=pending" json:"pending,omitempty"`
	Active  *Firmware `protobuf:"bytes,3,opt,name=active" json:"active,omitempty"`
}

func (m *FirmwareReply) Reset()                    { *m = FirmwareReply{} }
func (m *FirmwareReply) String() string            { return proto.CompactTextString(m) }
func (*FirmwareReply) ProtoMessage()               {}
func (*FirmwareReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FirmwareReply) GetGood() *Firmware {
	if m != nil {
		return m.Good
	}
	return nil
}

func (m *FirmwareReply) GetPending() *Firmware {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *FirmwareReply) GetActive() *Firmware {
	if m != nil {
		return m.Active
	}
	return nil
}

type SensorCapabilities struct {
	Id            int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UnitOfMeasure string `protobuf:"bytes,3,opt,name=unitOfMeasure" json:"unitOfMeasure,omitempty"`
}

func (m *SensorCapabilities) Reset()                    { *m = SensorCapabilities{} }
func (m *SensorCapabilities) String() string            { return proto.CompactTextString(m) }
func (*SensorCapabilities) ProtoMessage()               {}
func (*SensorCapabilities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SensorCapabilities) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SensorCapabilities) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SensorCapabilities) GetUnitOfMeasure() string {
	if m != nil {
		return m.UnitOfMeasure
	}
	return ""
}

type BeginTakeReadings struct {
	Index      int32  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	CallerTime uint32 `protobuf:"varint,2,opt,name=callerTime" json:"callerTime,omitempty"`
	Number     uint32 `protobuf:"varint,3,opt,name=number" json:"number,omitempty"`
}

func (m *BeginTakeReadings) Reset()                    { *m = BeginTakeReadings{} }
func (m *BeginTakeReadings) String() string            { return proto.CompactTextString(m) }
func (*BeginTakeReadings) ProtoMessage()               {}
func (*BeginTakeReadings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BeginTakeReadings) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BeginTakeReadings) GetCallerTime() uint32 {
	if m != nil {
		return m.CallerTime
	}
	return 0
}

func (m *BeginTakeReadings) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type QueryReadingStatus struct {
	Sleep uint32 `protobuf:"varint,1,opt,name=sleep" json:"sleep,omitempty"`
}

func (m *QueryReadingStatus) Reset()                    { *m = QueryReadingStatus{} }
func (m *QueryReadingStatus) String() string            { return proto.CompactTextString(m) }
func (*QueryReadingStatus) ProtoMessage()               {}
func (*QueryReadingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryReadingStatus) GetSleep() uint32 {
	if m != nil {
		return m.Sleep
	}
	return 0
}

type ReadingStatus struct {
	State   ReadingState `protobuf:"varint,1,opt,name=state,enum=fk_module.ReadingState" json:"state,omitempty"`
	Backoff uint32       `protobuf:"varint,2,opt,name=backoff" json:"backoff,omitempty"`
	Elapsed uint32       `protobuf:"varint,3,opt,name=elapsed" json:"elapsed,omitempty"`
}

func (m *ReadingStatus) Reset()                    { *m = ReadingStatus{} }
func (m *ReadingStatus) String() string            { return proto.CompactTextString(m) }
func (*ReadingStatus) ProtoMessage()               {}
func (*ReadingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadingStatus) GetState() ReadingState {
	if m != nil {
		return m.State
	}
	return ReadingState_IDLE
}

func (m *ReadingStatus) GetBackoff() uint32 {
	if m != nil {
		return m.Backoff
	}
	return 0
}

func (m *ReadingStatus) GetElapsed() uint32 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

type SensorReadings struct {
}

func (m *SensorReadings) Reset()                    { *m = SensorReadings{} }
func (m *SensorReadings) String() string            { return proto.CompactTextString(m) }
func (*SensorReadings) ProtoMessage()               {}
func (*SensorReadings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SensorReading struct {
	Sensor int32   `protobuf:"varint,1,opt,name=sensor" json:"sensor,omitempty"`
	Time   uint32  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Value  float32 `protobuf:"fixed32,3,opt,name=value" json:"value,omitempty"`
}

func (m *SensorReading) Reset()                    { *m = SensorReading{} }
func (m *SensorReading) String() string            { return proto.CompactTextString(m) }
func (*SensorReading) ProtoMessage()               {}
func (*SensorReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SensorReading) GetSensor() int32 {
	if m != nil {
		return m.Sensor
	}
	return 0
}

func (m *SensorReading) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SensorReading) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Custom struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Custom) Reset()                    { *m = Custom{} }
func (m *Custom) String() string            { return proto.CompactTextString(m) }
func (*Custom) ProtoMessage()               {}
func (*Custom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Custom) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type Data struct {
	Size     int32  `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Kind     int32  `protobuf:"varint,3,opt,name=kind" json:"kind,omitempty"`
	Checksum []byte `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Bank     int32  `protobuf:"varint,5,opt,name=bank" json:"bank,omitempty"`
	Etag     string `protobuf:"bytes,6,opt,name=etag" json:"etag,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Data) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *Data) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *Data) GetBank() int32 {
	if m != nil {
		return m.Bank
	}
	return 0
}

func (m *Data) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type DataStatus struct {
	Size int32 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
}

func (m *DataStatus) Reset()                    { *m = DataStatus{} }
func (m *DataStatus) String() string            { return proto.CompactTextString(m) }
func (*DataStatus) ProtoMessage()               {}
func (*DataStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DataStatus) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type BeginTransmission struct {
	Kind int32 `protobuf:"varint,1,opt,name=kind" json:"kind,omitempty"`
}

func (m *BeginTransmission) Reset()                    { *m = BeginTransmission{} }
func (m *BeginTransmission) String() string            { return proto.CompactTextString(m) }
func (*BeginTransmission) ProtoMessage()               {}
func (*BeginTransmission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BeginTransmission) GetKind() int32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

type QueryTransmissionStatus struct {
}

func (m *QueryTransmissionStatus) Reset()                    { *m = QueryTransmissionStatus{} }
func (m *QueryTransmissionStatus) String() string            { return proto.CompactTextString(m) }
func (*QueryTransmissionStatus) ProtoMessage()               {}
func (*QueryTransmissionStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type TransmissionStatus struct {
	State TransmissionState `protobuf:"varint,1,opt,name=state,enum=fk_module.TransmissionState" json:"state,omitempty"`
}

func (m *TransmissionStatus) Reset()                    { *m = TransmissionStatus{} }
func (m *TransmissionStatus) String() string            { return proto.CompactTextString(m) }
func (*TransmissionStatus) ProtoMessage()               {}
func (*TransmissionStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TransmissionStatus) GetState() TransmissionState {
	if m != nil {
		return m.State
	}
	return TransmissionState_TRANSMISSION_IDLE
}

type WireMessageQuery struct {
	Type                    QueryType                `protobuf:"varint,1,opt,name=type,enum=fk_module.QueryType" json:"type,omitempty"`
	QueryCapabilities       *QueryCapabilities       `protobuf:"bytes,2,opt,name=queryCapabilities" json:"queryCapabilities,omitempty"`
	QuerySensorCapabilities *QuerySensorCapabilities `protobuf:"bytes,3,opt,name=querySensorCapabilities" json:"querySensorCapabilities,omitempty"`
	BeginTakeReadings       *BeginTakeReadings       `protobuf:"bytes,4,opt,name=beginTakeReadings" json:"beginTakeReadings,omitempty"`
	QueryReadingStatus      *QueryReadingStatus      `protobuf:"bytes,5,opt,name=queryReadingStatus" json:"queryReadingStatus,omitempty"`
	Custom                  *Custom                  `protobuf:"bytes,6,opt,name=custom" json:"custom,omitempty"`
	Data                    *Data                    `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
	BeginTransmission       *BeginTransmission       `protobuf:"bytes,8,opt,name=beginTransmission" json:"beginTransmission,omitempty"`
	QueryTransmissionStatus *QueryTransmissionStatus `protobuf:"bytes,9,opt,name=queryTransmissionStatus" json:"queryTransmissionStatus,omitempty"`
}

func (m *WireMessageQuery) Reset()                    { *m = WireMessageQuery{} }
func (m *WireMessageQuery) String() string            { return proto.CompactTextString(m) }
func (*WireMessageQuery) ProtoMessage()               {}
func (*WireMessageQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *WireMessageQuery) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_QUERY_NONE
}

func (m *WireMessageQuery) GetQueryCapabilities() *QueryCapabilities {
	if m != nil {
		return m.QueryCapabilities
	}
	return nil
}

func (m *WireMessageQuery) GetQuerySensorCapabilities() *QuerySensorCapabilities {
	if m != nil {
		return m.QuerySensorCapabilities
	}
	return nil
}

func (m *WireMessageQuery) GetBeginTakeReadings() *BeginTakeReadings {
	if m != nil {
		return m.BeginTakeReadings
	}
	return nil
}

func (m *WireMessageQuery) GetQueryReadingStatus() *QueryReadingStatus {
	if m != nil {
		return m.QueryReadingStatus
	}
	return nil
}

func (m *WireMessageQuery) GetCustom() *Custom {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *WireMessageQuery) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WireMessageQuery) GetBeginTransmission() *BeginTransmission {
	if m != nil {
		return m.BeginTransmission
	}
	return nil
}

func (m *WireMessageQuery) GetQueryTransmissionStatus() *QueryTransmissionStatus {
	if m != nil {
		return m.QueryTransmissionStatus
	}
	return nil
}

type Error struct {
	Type    ErrorType `protobuf:"varint,1,opt,name=type,enum=fk_module.ErrorType" json:"type,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Error) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_NONE
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type WireMessageReply struct {
	Type               ReplyType           `protobuf:"varint,1,opt,name=type,enum=fk_module.ReplyType" json:"type,omitempty"`
	Error              *Error              `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Capabilities       *Capabilities       `protobuf:"bytes,3,opt,name=capabilities" json:"capabilities,omitempty"`
	SensorCapabilities *SensorCapabilities `protobuf:"bytes,4,opt,name=sensorCapabilities" json:"sensorCapabilities,omitempty"`
	ReadingStatus      *ReadingStatus      `protobuf:"bytes,5,opt,name=readingStatus" json:"readingStatus,omitempty"`
	SensorReading      *SensorReading      `protobuf:"bytes,6,opt,name=sensorReading" json:"sensorReading,omitempty"`
	Custom             *Custom             `protobuf:"bytes,7,opt,name=custom" json:"custom,omitempty"`
	Data               *DataStatus         `protobuf:"bytes,8,opt,name=data" json:"data,omitempty"`
	TransmissionStatus *TransmissionStatus `protobuf:"bytes,9,opt,name=transmissionStatus" json:"transmissionStatus,omitempty"`
	Firmware           *FirmwareReply      `protobuf:"bytes,10,opt,name=firmware" json:"firmware,omitempty"`
}

func (m *WireMessageReply) Reset()                    { *m = WireMessageReply{} }
func (m *WireMessageReply) String() string            { return proto.CompactTextString(m) }
func (*WireMessageReply) ProtoMessage()               {}
func (*WireMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *WireMessageReply) GetType() ReplyType {
	if m != nil {
		return m.Type
	}
	return ReplyType_REPLY_NONE
}

func (m *WireMessageReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *WireMessageReply) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *WireMessageReply) GetSensorCapabilities() *SensorCapabilities {
	if m != nil {
		return m.SensorCapabilities
	}
	return nil
}

func (m *WireMessageReply) GetReadingStatus() *ReadingStatus {
	if m != nil {
		return m.ReadingStatus
	}
	return nil
}

func (m *WireMessageReply) GetSensorReading() *SensorReading {
	if m != nil {
		return m.SensorReading
	}
	return nil
}

func (m *WireMessageReply) GetCustom() *Custom {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *WireMessageReply) GetData() *DataStatus {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WireMessageReply) GetTransmissionStatus() *TransmissionStatus {
	if m != nil {
		return m.TransmissionStatus
	}
	return nil
}

func (m *WireMessageReply) GetFirmware() *FirmwareReply {
	if m != nil {
		return m.Firmware
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCapabilities)(nil), "fk_module.QueryCapabilities")
	proto.RegisterType((*QuerySensorCapabilities)(nil), "fk_module.QuerySensorCapabilities")
	proto.RegisterType((*Firmware)(nil), "fk_module.Firmware")
	proto.RegisterType((*Capabilities)(nil), "fk_module.Capabilities")
	proto.RegisterType((*FirmwareReply)(nil), "fk_module.FirmwareReply")
	proto.RegisterType((*SensorCapabilities)(nil), "fk_module.SensorCapabilities")
	proto.RegisterType((*BeginTakeReadings)(nil), "fk_module.BeginTakeReadings")
	proto.RegisterType((*QueryReadingStatus)(nil), "fk_module.QueryReadingStatus")
	proto.RegisterType((*ReadingStatus)(nil), "fk_module.ReadingStatus")
	proto.RegisterType((*SensorReadings)(nil), "fk_module.SensorReadings")
	proto.RegisterType((*SensorReading)(nil), "fk_module.SensorReading")
	proto.RegisterType((*Custom)(nil), "fk_module.Custom")
	proto.RegisterType((*Data)(nil), "fk_module.Data")
	proto.RegisterType((*DataStatus)(nil), "fk_module.DataStatus")
	proto.RegisterType((*BeginTransmission)(nil), "fk_module.BeginTransmission")
	proto.RegisterType((*QueryTransmissionStatus)(nil), "fk_module.QueryTransmissionStatus")
	proto.RegisterType((*TransmissionStatus)(nil), "fk_module.TransmissionStatus")
	proto.RegisterType((*WireMessageQuery)(nil), "fk_module.WireMessageQuery")
	proto.RegisterType((*Error)(nil), "fk_module.Error")
	proto.RegisterType((*WireMessageReply)(nil), "fk_module.WireMessageReply")
	proto.RegisterEnum("fk_module.QueryType", QueryType_name, QueryType_value)
	proto.RegisterEnum("fk_module.ReplyType", ReplyType_name, ReplyType_value)
	proto.RegisterEnum("fk_module.ModuleType", ModuleType_name, ModuleType_value)
	proto.RegisterEnum("fk_module.ReadingState", ReadingState_name, ReadingState_value)
	proto.RegisterEnum("fk_module.RequiredUptime", RequiredUptime_name, RequiredUptime_value)
	proto.RegisterEnum("fk_module.TransmissionState", TransmissionState_name, TransmissionState_value)
	proto.RegisterEnum("fk_module.ErrorType", ErrorType_name, ErrorType_value)
}

func init() { proto.RegisterFile("fk-module.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xeb, 0x8e, 0x1a, 0xc7,
	0x12, 0x36, 0x2c, 0xd7, 0x5a, 0x60, 0x9b, 0x3e, 0x6b, 0x2f, 0x3e, 0xb2, 0x8f, 0xac, 0x39, 0x51,
	0xbc, 0x26, 0xb1, 0xad, 0x6c, 0x22, 0x25, 0x52, 0xa4, 0x48, 0xb3, 0x30, 0x76, 0x88, 0x61, 0xc0,
	0x3d, 0x10, 0x67, 0xa5, 0x28, 0x68, 0x80, 0x66, 0x33, 0x82, 0x19, 0xd8, 0xb9, 0x38, 0xd9, 0x3c,
	0x80, 0x9f, 0x20, 0x4f, 0x95, 0x3c, 0x4e, 0x7e, 0xe6, 0x4f, 0xd4, 0x97, 0x19, 0xe6, 0x02, 0x76,
	0x7e, 0x6d, 0x57, 0xf5, 0xd7, 0x55, 0x5f, 0x57, 0x7d, 0x5d, 0xcc, 0xc2, 0xc9, 0x72, 0xf5, 0xd4,
	0xde, 0x2c, 0x82, 0x35, 0x7d, 0xb6, 0x75, 0x37, 0xfe, 0x06, 0x57, 0x97, 0xab, 0xa9, 0x70, 0x28,
	0x03, 0x68, 0xbe, 0x0e, 0xa8, 0x7b, 0xdb, 0x31, 0xb7, 0xe6, 0xcc, 0x5a, 0x5b, 0xbe, 0x45, 0x3d,
	0xdc, 0x82, 0xf2, 0x5b, 0xea, 0x7a, 0xd6, 0xc6, 0x69, 0xe5, 0x1e, 0xe5, 0xce, 0x8b, 0x24, 0x34,
	0xf1, 0xff, 0x00, 0xe6, 0xe6, 0x7a, 0x4d, 0xdd, 0xb1, 0x65, 0xd3, 0x56, 0xfe, 0x51, 0xee, 0xbc,
	0x4e, 0x62, 0x1e, 0xe5, 0x33, 0x38, 0xe3, 0xe1, 0x0c, 0xea, 0x78, 0x1b, 0x37, 0x11, 0xf4, 0x1e,
	0x94, 0x3c, 0xee, 0x95, 0x31, 0xa5, 0xa5, 0x38, 0x50, 0x79, 0x61, 0xb9, 0xf6, 0x2f, 0xa6, 0x4b,
	0x31, 0x82, 0xa3, 0x6b, 0xcb, 0xe7, 0x80, 0x2a, 0x61, 0x4b, 0x7c, 0x0a, 0xc5, 0x59, 0x60, 0xad,
	0x17, 0x3c, 0x57, 0x95, 0x08, 0x03, 0x63, 0x28, 0x78, 0xd6, 0x6f, 0xb4, 0x75, 0xc4, 0x09, 0xf0,
	0x35, 0xf3, 0x51, 0xdf, 0xbc, 0x6e, 0x15, 0x38, 0x90, 0xaf, 0x99, 0xcf, 0x67, 0x44, 0x8b, 0x02,
	0xc7, 0xd6, 0xca, 0x5f, 0x79, 0xa8, 0xfd, 0xcb, 0xdb, 0x3e, 0x81, 0x82, 0x7f, 0xbb, 0x15, 0xf7,
	0x6c, 0x5c, 0xdc, 0x7d, 0x16, 0x95, 0xed, 0xd9, 0x80, 0xff, 0x19, 0xdf, 0x6e, 0x29, 0xe1, 0x10,
	0x96, 0xc9, 0x31, 0x6d, 0xc1, 0xa8, 0x4a, 0xf8, 0x9a, 0xdd, 0x58, 0xc0, 0x5b, 0x65, 0xee, 0x95,
	0x16, 0x3e, 0x87, 0x13, 0x27, 0xb0, 0x67, 0xd4, 0x1d, 0x2e, 0x45, 0x9d, 0x3c, 0x4e, 0xba, 0x48,
	0xd2, 0x6e, 0xfc, 0x1c, 0x2a, 0x4b, 0x59, 0x1b, 0x7e, 0x87, 0xe3, 0x8b, 0xff, 0xc4, 0x48, 0x84,
	0x65, 0x23, 0x11, 0x08, 0x7f, 0x05, 0x67, 0xb6, 0xe5, 0x58, 0x76, 0x60, 0xeb, 0x32, 0x14, 0xa1,
	0xe6, 0xc2, 0x72, 0xae, 0xbd, 0x56, 0x89, 0xa7, 0x38, 0xb4, 0x8d, 0xff, 0x0b, 0x95, 0xf9, 0xc6,
	0xde, 0x5a, 0x6b, 0xba, 0x68, 0x55, 0x78, 0xb9, 0x22, 0x1b, 0xab, 0xd0, 0x70, 0xe9, 0x4d, 0x60,
	0xb9, 0x74, 0x31, 0xd9, 0xf2, 0x82, 0x56, 0x79, 0x45, 0xee, 0xc7, 0xc8, 0x90, 0x04, 0x80, 0xa4,
	0x0e, 0x28, 0xbf, 0xe7, 0xa0, 0x1e, 0xf1, 0xa5, 0xdb, 0xf5, 0x2d, 0x7e, 0x0c, 0x85, 0xeb, 0xcd,
	0x66, 0xc1, 0x6b, 0x7e, 0xe0, 0x5e, 0x1c, 0x80, 0x9f, 0x42, 0x79, 0x4b, 0x1d, 0xc6, 0x92, 0x37,
	0xe2, 0x00, 0x36, 0xc4, 0xe0, 0x4f, 0xa0, 0x64, 0xce, 0x7d, 0xeb, 0xad, 0xe8, 0xc5, 0x01, 0xb4,
	0x84, 0x28, 0x3f, 0x01, 0xde, 0x23, 0xd5, 0x06, 0xe4, 0xad, 0x85, 0x14, 0x43, 0xde, 0x5a, 0x44,
	0xcd, 0xcd, 0xc7, 0x9a, 0xfb, 0x11, 0xd4, 0x03, 0xc7, 0xf2, 0x87, 0xcb, 0x01, 0x35, 0xbd, 0xc0,
	0x0d, 0x3b, 0x9f, 0x74, 0x2a, 0x26, 0x34, 0x2f, 0xe9, 0xb5, 0xe5, 0x8c, 0xcd, 0x15, 0x8d, 0x4a,
	0x7d, 0x0a, 0x45, 0xcb, 0x59, 0xd0, 0x5f, 0x65, 0x06, 0x61, 0x7c, 0xe8, 0x69, 0x31, 0x35, 0x09,
	0x79, 0x48, 0xd5, 0x4b, 0x4b, 0x69, 0x03, 0xe6, 0x4f, 0x4e, 0x86, 0x37, 0x7c, 0xd3, 0x0f, 0x78,
	0x0e, 0x6f, 0x4d, 0xe9, 0x96, 0xe7, 0xa8, 0x13, 0x61, 0x28, 0x2e, 0xd4, 0x93, 0xb0, 0xa7, 0x50,
	0xf4, 0x7c, 0xd3, 0xa7, 0x1c, 0xd6, 0xb8, 0x38, 0x4b, 0x34, 0x34, 0x02, 0x52, 0x22, 0x50, 0xec,
	0xa9, 0xcc, 0xcc, 0xf9, 0x6a, 0xb3, 0x5c, 0x4a, 0x82, 0xa1, 0xc9, 0x76, 0xe8, 0xda, 0xdc, 0x7a,
	0x74, 0x21, 0xe9, 0x85, 0xa6, 0x82, 0xa0, 0x21, 0x4a, 0x1c, 0xde, 0x5f, 0x79, 0x0d, 0xf5, 0x84,
	0xe7, 0xd0, 0x68, 0x88, 0x9e, 0x6f, 0x7e, 0xf7, 0x7c, 0xd9, 0xc5, 0xde, 0x9a, 0xeb, 0x40, 0xd4,
	0x3b, 0x4f, 0x84, 0xa1, 0x28, 0x50, 0xea, 0x04, 0x9e, 0xbf, 0xb1, 0x19, 0x11, 0x9b, 0x7a, 0x9e,
	0x79, 0x2d, 0xee, 0x54, 0x23, 0xa1, 0xa9, 0xbc, 0xcb, 0x41, 0xa1, 0x6b, 0xfa, 0x66, 0x34, 0x3d,
	0x44, 0xb2, 0x68, 0x7a, 0x2c, 0x4c, 0xdf, 0xe4, 0xa9, 0x6a, 0x84, 0xaf, 0x99, 0x6f, 0x65, 0x39,
	0xe2, 0x42, 0x45, 0xc2, 0xd7, 0xfc, 0x99, 0xfc, 0x4c, 0xe7, 0x2b, 0x2f, 0xb0, 0xf9, 0xa3, 0xad,
	0x91, 0xc8, 0x66, 0xf8, 0x99, 0xe9, 0xac, 0xf8, 0x4b, 0x2d, 0x12, 0xbe, 0x8e, 0xa6, 0x52, 0x69,
	0x37, 0x95, 0x94, 0x47, 0x00, 0x8c, 0x87, 0x6c, 0xc1, 0x1e, 0x36, 0xca, 0xe3, 0x50, 0x36, 0xae,
	0xe9, 0x78, 0xb6, 0xe5, 0xf1, 0x69, 0x14, 0xd2, 0xc9, 0xed, 0xe8, 0x28, 0xf7, 0xe5, 0xbc, 0x8d,
	0x03, 0x45, 0x5c, 0xe5, 0x5b, 0xc0, 0x59, 0x2f, 0xbe, 0x48, 0x36, 0xfc, 0x41, 0xac, 0xe1, 0x69,
	0x74, 0xd8, 0x75, 0xe5, 0xef, 0x02, 0xa0, 0x37, 0x96, 0x4b, 0x07, 0xa2, 0x90, 0x3c, 0x21, 0x3e,
	0x97, 0xb3, 0x51, 0xc4, 0x39, 0x8d, 0xc5, 0x11, 0x84, 0x76, 0xa3, 0xf1, 0x3b, 0x68, 0xde, 0xa4,
	0x7f, 0x62, 0xe4, 0x4b, 0x7e, 0x90, 0x3e, 0x16, 0xc7, 0x90, 0xec, 0x31, 0xfc, 0x23, 0x9c, 0xdd,
	0xec, 0xff, 0x7d, 0x91, 0xaf, 0x5d, 0x49, 0x47, 0xcc, 0x22, 0xc9, 0xa1, 0x10, 0x8c, 0xe9, 0x2c,
	0xfd, 0x5a, 0x79, 0x97, 0x93, 0x4c, 0x33, 0x2f, 0x9a, 0x64, 0x8f, 0xe1, 0x01, 0xe0, 0x9b, 0xcc,
	0xb3, 0x94, 0x43, 0xfc, 0x61, 0x9a, 0x64, 0x02, 0x44, 0xf6, 0x1c, 0xc4, 0x4f, 0xa0, 0x34, 0xe7,
	0x02, 0xe7, 0x4a, 0x3a, 0xbe, 0x68, 0xc6, 0x42, 0x08, 0xe5, 0x13, 0x09, 0xc0, 0xff, 0x97, 0x52,
	0x2e, 0x73, 0xe0, 0x49, 0x0c, 0xc8, 0x54, 0x27, 0xb5, 0x1d, 0x5d, 0x35, 0xd6, 0x74, 0x3e, 0xf7,
	0xf7, 0x5d, 0x35, 0x86, 0x21, 0xd9, 0x63, 0x51, 0x53, 0xb2, 0x72, 0xe3, 0xbf, 0x13, 0x7b, 0x9a,
	0x92, 0x45, 0x92, 0x43, 0x21, 0x94, 0x57, 0x50, 0xd4, 0x5c, 0x77, 0xe3, 0xbe, 0x47, 0x71, 0x7c,
	0x3f, 0xa6, 0xb8, 0xd8, 0x0c, 0x10, 0x23, 0x3b, 0x9a, 0x01, 0x7f, 0x26, 0xa5, 0x2c, 0x7e, 0x89,
	0x0e, 0x07, 0xe6, 0xfb, 0xb1, 0xc0, 0x1f, 0x43, 0x91, 0xb2, 0x5c, 0x52, 0xbe, 0x28, 0xcd, 0x81,
	0x88, 0x6d, 0xfc, 0x35, 0xd4, 0xe6, 0x59, 0x6d, 0xc6, 0xa7, 0x6b, 0x42, 0x90, 0x09, 0x30, 0x53,
	0x8e, 0x97, 0x95, 0x77, 0x21, 0xa3, 0x9c, 0x3d, 0xca, 0xde, 0x73, 0x10, 0x7f, 0x03, 0x75, 0x77,
	0x8f, 0x06, 0x5b, 0xfb, 0x47, 0x7d, 0xe0, 0x91, 0x24, 0x9c, 0x9d, 0xf7, 0xe2, 0xd3, 0x5a, 0x0a,
	0xb0, 0x95, 0x61, 0x22, 0xf7, 0x49, 0x12, 0x1e, 0x53, 0x6e, 0xf9, 0x43, 0xca, 0x7d, 0x22, 0x95,
	0x2b, 0x74, 0x78, 0x37, 0xa5, 0x5c, 0x49, 0x4f, 0xe8, 0x77, 0x00, 0xd8, 0x3f, 0x24, 0xb7, 0x87,
	0xef, 0x19, 0x6a, 0xec, 0x79, 0x65, 0x0f, 0xe2, 0x2f, 0x62, 0x1f, 0x5a, 0x90, 0xb9, 0x5f, 0xe2,
	0xc3, 0x65, 0xf7, 0xb5, 0xd5, 0xfe, 0x23, 0x0f, 0xd5, 0x68, 0xda, 0xe1, 0x06, 0xc0, 0xeb, 0x89,
	0x46, 0xae, 0xa6, 0xfa, 0x50, 0xd7, 0xd0, 0x1d, 0x7c, 0x0f, 0xb0, 0xb0, 0x3b, 0xea, 0x48, 0xbd,
	0xec, 0xf5, 0x7b, 0xe3, 0x9e, 0x66, 0xa0, 0x1c, 0x7e, 0x08, 0xf7, 0x85, 0xdf, 0xd0, 0x74, 0x63,
	0x48, 0x92, 0xdb, 0xf9, 0xdd, 0xf6, 0xa5, 0xf6, 0xb2, 0xa7, 0x4f, 0xc7, 0xea, 0x2b, 0x6d, 0x4a,
	0x34, 0xb5, 0xdb, 0xd3, 0x5f, 0x1a, 0xe8, 0x08, 0xb7, 0xe0, 0x54, 0x6c, 0x4b, 0xdf, 0xd4, 0x18,
	0xab, 0xe3, 0x89, 0x81, 0x0a, 0x18, 0x41, 0x4d, 0xe6, 0x9b, 0x18, 0xe3, 0xe1, 0x00, 0x15, 0xf1,
	0x5d, 0x68, 0x0a, 0x4f, 0x57, 0x1d, 0xab, 0x53, 0x75, 0x34, 0xd2, 0xf4, 0x2e, 0x2a, 0xe1, 0x53,
	0x40, 0x31, 0x77, 0xa7, 0xaf, 0xa9, 0x04, 0x95, 0xf1, 0x03, 0x68, 0x25, 0xf2, 0x12, 0x55, 0x37,
	0x06, 0x3d, 0xc3, 0xe8, 0x0d, 0x75, 0x54, 0xd9, 0xb1, 0x8a, 0xfb, 0xc3, 0xdc, 0xd5, 0xdd, 0x5d,
	0x79, 0xc8, 0x11, 0xd1, 0x46, 0x2a, 0xd1, 0x10, 0xa4, 0x18, 0x7c, 0xaf, 0x91, 0xde, 0x8b, 0x2b,
	0x74, 0x8c, 0x31, 0x34, 0x84, 0xfb, 0x45, 0x8f, 0x0c, 0xde, 0x30, 0x68, 0xad, 0xfd, 0x2e, 0x0f,
	0xd5, 0xe8, 0xbd, 0xb1, 0x62, 0x12, 0x6d, 0xd4, 0x8f, 0x8a, 0x79, 0x02, 0xc7, 0xc2, 0x26, 0xda,
	0x98, 0x5c, 0xa1, 0xdc, 0xce, 0xa1, 0x11, 0x32, 0x24, 0x28, 0xcf, 0x28, 0x08, 0x47, 0xa2, 0x9e,
	0x47, 0x8c, 0xb9, 0xf0, 0xef, 0x2b, 0x77, 0x81, 0xd5, 0x33, 0x0c, 0x9c, 0xa8, 0x67, 0x91, 0xd5,
	0x53, 0x06, 0x14, 0xf5, 0x2c, 0xed, 0x48, 0xb1, 0xdb, 0xa0, 0xf2, 0x2e, 0xf4, 0xbe, 0xa2, 0x54,
	0x70, 0x13, 0xea, 0x32, 0xf3, 0xa4, 0xd3, 0xd1, 0x0c, 0x56, 0xa7, 0x28, 0xc2, 0xe5, 0xc4, 0xb8,
	0x42, 0xc0, 0x0a, 0x21, 0xec, 0xa8, 0x10, 0xc7, 0xed, 0x4f, 0x01, 0x76, 0xff, 0x5e, 0x60, 0x80,
	0x92, 0x20, 0x8e, 0xee, 0x30, 0x74, 0x67, 0x38, 0x18, 0x4c, 0xf4, 0x5e, 0x47, 0x1d, 0xf7, 0x86,
	0xba, 0x81, 0x72, 0xed, 0x2f, 0xa1, 0x16, 0xff, 0x52, 0xc3, 0x15, 0x28, 0xf4, 0xba, 0x7d, 0x56,
	0xb2, 0x2a, 0x14, 0x79, 0x2b, 0x51, 0x8e, 0x39, 0x79, 0xc2, 0x3c, 0x5b, 0x75, 0x59, 0x45, 0x8f,
	0xda, 0xcf, 0xa1, 0x91, 0xfc, 0x66, 0x67, 0xa9, 0xd4, 0xfe, 0x1b, 0xf5, 0xca, 0x40, 0x77, 0x04,
	0x77, 0x21, 0xba, 0xe9, 0x50, 0xef, 0x5f, 0xa1, 0x5c, 0x7b, 0x0b, 0xcd, 0xcc, 0x27, 0x02, 0x6b,
	0x70, 0xe2, 0xf2, 0x32, 0xf7, 0x3d, 0xc0, 0x09, 0x77, 0x48, 0x24, 0x0d, 0x97, 0xac, 0xd2, 0x6e,
	0x49, 0xf1, 0x02, 0xaa, 0xd1, 0x68, 0x67, 0xcc, 0xa5, 0x16, 0x8e, 0xa1, 0xfc, 0x52, 0xd3, 0x35,
	0xa2, 0xf6, 0x51, 0x8e, 0x55, 0x74, 0xa2, 0x6b, 0x3f, 0x8c, 0xb4, 0xce, 0x58, 0xeb, 0xa2, 0xfc,
	0xac, 0xc4, 0xff, 0xc5, 0xfd, 0xfc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xb1, 0x73, 0xf6,
	0xf5, 0x0e, 0x00, 0x00,
}
