/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Thu Aug 16 12:47:13 2018. */

#include "fk-module.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fk_module_QueryCapabilities_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_QueryCapabilities, version, version, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_QueryCapabilities, callerTime, version, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_QuerySensorCapabilities_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_QuerySensorCapabilities, sensor, sensor, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_Firmware_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, fk_module_Firmware, git, git, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_Firmware, build, git, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_Capabilities_fields[8] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_Capabilities, version, version, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, fk_module_Capabilities, type, version, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_Capabilities, name, type, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, fk_module_Capabilities, numberOfSensors, name, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_Capabilities, firmware, numberOfSensors, &fk_module_Firmware_fields),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, fk_module_Capabilities, minimumNumberOfReadings, firmware, 0),
    PB_FIELD(  7, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_Capabilities, module, minimumNumberOfReadings, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_SensorCapabilities_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_SensorCapabilities, id, id, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_SensorCapabilities, name, id, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_SensorCapabilities, unitOfMeasure, name, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_BeginTakeReadings_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_BeginTakeReadings, index, index, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_BeginTakeReadings, callerTime, index, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_BeginTakeReadings, number, callerTime, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_QueryReadingStatus_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fk_module_QueryReadingStatus, sleep, sleep, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_ReadingStatus_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_module_ReadingStatus, state, state, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_ReadingStatus, backoff, state, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_ReadingStatus, elapsed, backoff, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_SensorReadings_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t fk_module_SensorReading_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_SensorReading, sensor, sensor, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fk_module_SensorReading, time, sensor, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, fk_module_SensorReading, value, time, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_Custom_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, fk_module_Custom, message, message, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_Data_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_Data, size, size, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, fk_module_Data, data, size, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, fk_module_Data, kind, data, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, fk_module_Data, checksum, kind, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, fk_module_Data, bank, checksum, 0),
    PB_FIELD(  6, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_Data, etag, bank, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_DataStatus_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_DataStatus, size, size, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_BeginTransmission_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fk_module_BeginTransmission, kind, kind, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_QueryTransmissionStatus_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t fk_module_TransmissionStatus_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_module_TransmissionStatus, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_WireMessageQuery_fields[10] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_module_WireMessageQuery, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, queryCapabilities, type, &fk_module_QueryCapabilities_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, querySensorCapabilities, queryCapabilities, &fk_module_QuerySensorCapabilities_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, beginTakeReadings, querySensorCapabilities, &fk_module_BeginTakeReadings_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, queryReadingStatus, beginTakeReadings, &fk_module_QueryReadingStatus_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, custom, queryReadingStatus, &fk_module_Custom_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, data, custom, &fk_module_Data_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, beginTransmission, data, &fk_module_BeginTransmission_fields),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageQuery, queryTransmissionStatus, beginTransmission, &fk_module_QueryTransmissionStatus_fields),
    PB_LAST_FIELD
};

const pb_field_t fk_module_Error_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_module_Error, type, type, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, fk_module_Error, message, type, 0),
    PB_LAST_FIELD
};

const pb_field_t fk_module_WireMessageReply_fields[10] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fk_module_WireMessageReply, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, error, type, &fk_module_Error_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, capabilities, error, &fk_module_Capabilities_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, sensorCapabilities, capabilities, &fk_module_SensorCapabilities_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, readingStatus, sensorCapabilities, &fk_module_ReadingStatus_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, sensorReading, readingStatus, &fk_module_SensorReading_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, custom, sensorReading, &fk_module_Custom_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, data, custom, &fk_module_DataStatus_fields),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, fk_module_WireMessageReply, transmissionStatus, data, &fk_module_TransmissionStatus_fields),
    PB_LAST_FIELD
};








/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_module_Capabilities, firmware) < 65536 && pb_membersize(fk_module_WireMessageQuery, queryCapabilities) < 65536 && pb_membersize(fk_module_WireMessageQuery, querySensorCapabilities) < 65536 && pb_membersize(fk_module_WireMessageQuery, beginTakeReadings) < 65536 && pb_membersize(fk_module_WireMessageQuery, queryReadingStatus) < 65536 && pb_membersize(fk_module_WireMessageQuery, custom) < 65536 && pb_membersize(fk_module_WireMessageQuery, data) < 65536 && pb_membersize(fk_module_WireMessageQuery, beginTransmission) < 65536 && pb_membersize(fk_module_WireMessageQuery, queryTransmissionStatus) < 65536 && pb_membersize(fk_module_WireMessageReply, error) < 65536 && pb_membersize(fk_module_WireMessageReply, capabilities) < 65536 && pb_membersize(fk_module_WireMessageReply, sensorCapabilities) < 65536 && pb_membersize(fk_module_WireMessageReply, readingStatus) < 65536 && pb_membersize(fk_module_WireMessageReply, sensorReading) < 65536 && pb_membersize(fk_module_WireMessageReply, custom) < 65536 && pb_membersize(fk_module_WireMessageReply, data) < 65536 && pb_membersize(fk_module_WireMessageReply, transmissionStatus) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_fk_module_QueryCapabilities_fk_module_QuerySensorCapabilities_fk_module_Firmware_fk_module_Capabilities_fk_module_SensorCapabilities_fk_module_BeginTakeReadings_fk_module_QueryReadingStatus_fk_module_ReadingStatus_fk_module_SensorReadings_fk_module_SensorReading_fk_module_Custom_fk_module_Data_fk_module_DataStatus_fk_module_BeginTransmission_fk_module_QueryTransmissionStatus_fk_module_TransmissionStatus_fk_module_WireMessageQuery_fk_module_Error_fk_module_WireMessageReply)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fk_module_Capabilities, firmware) < 256 && pb_membersize(fk_module_WireMessageQuery, queryCapabilities) < 256 && pb_membersize(fk_module_WireMessageQuery, querySensorCapabilities) < 256 && pb_membersize(fk_module_WireMessageQuery, beginTakeReadings) < 256 && pb_membersize(fk_module_WireMessageQuery, queryReadingStatus) < 256 && pb_membersize(fk_module_WireMessageQuery, custom) < 256 && pb_membersize(fk_module_WireMessageQuery, data) < 256 && pb_membersize(fk_module_WireMessageQuery, beginTransmission) < 256 && pb_membersize(fk_module_WireMessageQuery, queryTransmissionStatus) < 256 && pb_membersize(fk_module_WireMessageReply, error) < 256 && pb_membersize(fk_module_WireMessageReply, capabilities) < 256 && pb_membersize(fk_module_WireMessageReply, sensorCapabilities) < 256 && pb_membersize(fk_module_WireMessageReply, readingStatus) < 256 && pb_membersize(fk_module_WireMessageReply, sensorReading) < 256 && pb_membersize(fk_module_WireMessageReply, custom) < 256 && pb_membersize(fk_module_WireMessageReply, data) < 256 && pb_membersize(fk_module_WireMessageReply, transmissionStatus) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_fk_module_QueryCapabilities_fk_module_QuerySensorCapabilities_fk_module_Firmware_fk_module_Capabilities_fk_module_SensorCapabilities_fk_module_BeginTakeReadings_fk_module_QueryReadingStatus_fk_module_ReadingStatus_fk_module_SensorReadings_fk_module_SensorReading_fk_module_Custom_fk_module_Data_fk_module_DataStatus_fk_module_BeginTransmission_fk_module_QueryTransmissionStatus_fk_module_TransmissionStatus_fk_module_WireMessageQuery_fk_module_Error_fk_module_WireMessageReply)
#endif


/* @@protoc_insertion_point(eof) */
