/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "fk-module.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fk_module_QueryCapabilities, fk_module_QueryCapabilities, AUTO)


PB_BIND(fk_module_QuerySensorCapabilities, fk_module_QuerySensorCapabilities, AUTO)


PB_BIND(fk_module_Firmware, fk_module_Firmware, AUTO)


PB_BIND(fk_module_Capabilities, fk_module_Capabilities, AUTO)


PB_BIND(fk_module_FirmwareReply, fk_module_FirmwareReply, AUTO)


PB_BIND(fk_module_SensorCapabilities, fk_module_SensorCapabilities, AUTO)


PB_BIND(fk_module_BeginTakeReadings, fk_module_BeginTakeReadings, AUTO)


PB_BIND(fk_module_QueryReadingStatus, fk_module_QueryReadingStatus, AUTO)


PB_BIND(fk_module_ReadingStatus, fk_module_ReadingStatus, AUTO)


PB_BIND(fk_module_SensorReadings, fk_module_SensorReadings, AUTO)


PB_BIND(fk_module_SensorReading, fk_module_SensorReading, AUTO)


PB_BIND(fk_module_Custom, fk_module_Custom, AUTO)


PB_BIND(fk_module_Data, fk_module_Data, AUTO)


PB_BIND(fk_module_DataStatus, fk_module_DataStatus, AUTO)


PB_BIND(fk_module_BeginTransmission, fk_module_BeginTransmission, AUTO)


PB_BIND(fk_module_QueryTransmissionStatus, fk_module_QueryTransmissionStatus, AUTO)


PB_BIND(fk_module_TransmissionStatus, fk_module_TransmissionStatus, AUTO)


PB_BIND(fk_module_WireMessageQuery, fk_module_WireMessageQuery, AUTO)


PB_BIND(fk_module_Error, fk_module_Error, AUTO)


PB_BIND(fk_module_WireMessageReply, fk_module_WireMessageReply, 2)










/* @@protoc_insertion_point(eof) */
